version: "3"

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoints.sh
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app

  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./.docker/redis:/redis

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    build: .
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=redisimobe
    ports:
      - "8081:8081"
    depends_on:
      - redis
