version: "3.7"

services:
  app:
    image: node:14-alpine
    command: sh -c "yarn install && yarn typeorm migration:run && yarn run dev"
    build: .
    ports:
      - "3333:3333"
    environment:
      TYPEORM_DATABASE: postgres
      TYPEORM_HOST: postgres.imobe.docker
      TYPEORM_USER: postgres
      TYPEORM_PASS: postgres
      TYPEORM_DATABASE: server_imobe_flex
      HOST_PORT: 3333
      SECRET_KEY: ${SECRET_KEY}
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    hostname: postgres.imobe.docker
    image: postgres
    restart: always
    volumes:
      - ./.docker/dbdata:/data/db
      - ./.docker/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: server_imobe_flex
    ports:
      - "5432:5432"
