version: "3.7"

services:
  app:
    build: .
    command: yarn start
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app

  redis:
    image: redis
    container_name: imobe_redis
    ports:
      - 6379:6379

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  server:
    container_name: redis-imobe
    build:
      context: ./
    environment:
      REDIS_URL: redis:6379
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: 1000
    ports:
      - 5000:5000
    volumes:
      - ./:/var/app
    depends_on:
      - redis
