version: "3.7"

services:
  database:
    hostname: postgres.imobe.docker
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: server_imobe_flex
    volumes:
      - pgdata:/data/postgres
  app_development:
    build: .
    ports:
      - 3333:3333
    env_file:
      - .env.dev
      - .env
    volumes:
      - .:/usr/app
    depends_on:
      - database

volumes:
  pgdata:
    driver: local