FROM node:14-alpine

WORKDIR /usr/src/app

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install --silent && mv node_modules ../

COPY . .

EXPOSE 3333

RUN chown -R node /usr/src/app

USER node

CMD ["npm", "run", "dev"]
