version: "3.7"

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
      POSTGRES_DB: imobe
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: pgsql

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    build: .
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=redisimobe
    ports:
      - "8081:8081"

  app:
    container_name: imobe-api
    build: .
    command: npm start
    depends_on:
      - db
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
